version: '3'

services:
  rabbit:
    image: rabbitmq:3.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./buildscripts/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./buildscripts/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json"
      - "./.tmpdata/rabbit:/var/lib/rabbitmq/mnesia"

  redis:
    image: redis:5
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - "./.tmpdata/redis:/data"
    ports:
      - "6379:6379"

  events-api:
    image: oasis/events-api
    ports:
      - "8050:8050"
    volumes:
      - "./buildscripts/events-api.conf:/etc/oasis/events-api.conf"
    environment:
      - "WAIT_HOSTS=redis:6379,rabbit:5672"
    depends_on:
      - redis
      - rabbit

  stats-api:
    image: oasis/stats-api
    ports:
      - "8010:8010"
    volumes:
      - "./buildscripts/stats-api.conf:/etc/oasis/stats-api.conf"
      - "./buildscripts/stats-api.properties:/etc/oasis/stats-api.properties"
    environment:
      - "WAIT_HOSTS=redis:6379,rabbit:5672"
    depends_on:
      - redis
      - rabbit

  engine:
    image: oasis/engine
    environment:
      - "WAIT_HOSTS=redis:6379,rabbit:5672"
    volumes:
      - "./buildscripts/engine.conf:/etc/oasis/engine.conf"
    depends_on:
      - redis
      - rabbit