spring:
  profiles:
    active: dev

  devtools:
    restart: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oasis
    username: root
    password: root
    hikari:
      poolName: Hikari
      auto-commit: false


